name: ESIP2024
channels:
- conda-forge
dependencies:
- pip
- numpy
- python = 3.10
- netCDF4
- matplotlib
- jupyterlab
- cartopy
- xarray
- dask
- scipy
- pip:
  - git+https://github.com/pydap/pydap.git
  - jupyter-contrib-nbextensions



