name: ESIP2024
channels:
- conda-forge
dependencies:
- pip
- numpy
- python = 3.10
- netCDF4
- Ipython
- tqdm
- aiohttp
- pandas
- bokeh
- matplotlib
- shapely
- jupyterlab
- cartopy
- xarray
- dask
- scipy
- intake = 0.7
- intake-xarray
- pip:
  - git+https://github.com/pydap/pydap.git
  - jupyter-contrib-nbextensions
  - jupyterlab-rise



